### PR TITLE
Update traces with chainid and version

### PR DESCRIPTION
**Pull request by 29988122**
As discussed in https://github.com/scroll-tech/go-ethereum/pull/227#issuecomment-1455371502
Update test  traces with chainid and version, w/ l2geth alpha v1.9.

Todo: traces of bridge contracts needed to be update, too. Work w/ Haoyu to proceed.

### CODE REVIEW

**Comment by lispc** [comment]
I would suggest PR against goerli 0215 branch.  So traces and codes are consistent

**Comment by 29988122** [comment]
> I would suggest PR against goerli 0215 branch. So traces and codes are consistent

Agree & changed, thanks for the reminder!

**Review by lispc — APPROVED** [review]

**Review by mask-pp — DISMISSED** [review]

**Comment by HAOYUatHZ** [comment]
will be great if we start migrating to https://github.com/scroll-tech/test-traces and use it as a submodule?

and for bridge traces:
https://github.com/scroll-tech/scroll-zkevm/tree/update_traces/zkevm/tests/traces/bridge

1. you can easily tell what tx need to be sent according to the json file name (except 01~10.json)
1.1 send such a tx
1.2 figure out which block it's in
1.3 run your local node and get the trace of it

2. for 01~10.json:
we now fecth block traces of block 01~22

if you are interested,
you can connect to DB 
and look into https://blockscout.scroll.io/ 
and try to understand why we pick 01~22

**Comment by HAOYUatHZ** [comment]
and what about @lispc starting using these traces to test? when @29988122 is adding more traces, before this PR gets merged

**Comment by lispc** [comment]
> and what about @lispc starting using these traces to test? when @29988122 is adding more traces, before this PR gets merged

ok!

**Comment by lispc** [comment]
@29988122 hi Jerry since the our l2geth already fix the deletion proof problem i think the traces can be regenerated

**Comment by 29988122** [comment]
Got it, will regenerate and update the repo w/ latest l2geth.
Blocker of bridge traces seems to be fixed, so I'll also provide them.

**Comment by lispc** [comment]
change base branch to v0.3

**Comment by 29988122** [comment]
Closed. Continue via https://github.com/scroll-tech/scroll-zkevm/pull/142

**Pull request closed without merging**
