### PR TITLE
switch to latest develop + new mpt circuit

### PR DESCRIPTION
**Pull request by lispc**
when `make mock`, some constrains failed:

(1) <del>mpt lookup related. @z2trillion </del>
(2) <del> l1 fee related @noel2004 </del>
(3) <del>pi circuit @kunxian-xia  (using develop@zkevm-circuit also reports this err). It is possible to log::error more details early during assignment? </del> need to set COINBASE env var
(4) COINBASE=5300000000000000000000000000000000000005 RUST_LOG=debug cargo test --features prove_verify --release test_vk_same -- --exact --nocapture 2>&1 | tee vk.log.    The constant column of pi circuit, and the second last fixed column of zktrie circuit,     is not fixed.

### CODE REVIEW

**Comment by kunxian-xia** [comment]
These two errors are caused by not setting "COINBASE". There are two options for setting the env-var that come to my mind:
1. set it in some script to run prover;
2. put it in a file (maybe `.env` file?).

What do you think the best way to set the env var?

**Comment by kunxian-xia** [comment]
The bug in which the constant column of PI circuit is not fixed shall be fixed by this PR(https://github.com/scroll-tech/zkevm-circuits/pull/561).

**Comment by noel2004** [comment]
It seems that we still have no fixed assignment for `index` and `modulus_byte` col: @z2trillion 

https://github.com/scroll-tech/mpt-circuit/blob/f47013661d95de36be030dcb1afbf66349c27533/src/gadgets/canonical_representation.rs#L147

**Comment by noel2004** [comment]
> when `make mock`, some constrains failed:
> 
> (1) ~mpt lookup related. @z2trillion ~ (2) ~ l1 fee related @noel2004 ~ (3) ~pi circuit @kunxian-xia (using develop@zkevm-circuit also reports this err). It is possible to log::error more details early during assignment? ~ need to set COINBASE env var (4) COINBASE=5300000000000000000000000000000000000005 RUST_LOG=debug cargo test --features prove_verify --release test_vk_same -- --exact --nocapture 2>&1 | tee vk.log. The constant column of pi circuit, and the second last fixed column of zktrie circuit, is not fixed.

https://github.com/scroll-tech/mpt-circuit/pull/52 should fix the unfixed column in zktrie circuit

**Pull request merged**
